#!/bin/sh

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

exec tr \
    'qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM' \
    'fghjklzxcvbnmqwertyuiopasdFGHJKLZXCVBNMQWERTYUIOPASD'

# vim:ts=4 sts=4 sw=4 et
